# Site Settings
title: Ayodeji Lindblad
description: >
  Ayodeji Lindblad (MIT Math PhD, low-dimensional topology and discrete geometry): CV, contact info, papers, & talks.
baseurl: ''
url: 'https://ayodejilindblad.com'
permalink: pretty
og_image: "https://ayodejilindblad.com/resources/imgs/icon.jpg"
github_username: ayodejilindblad

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

github: [metadata]
encoding: UTF-8
kramdown:
 input: GFM
 hard_wrap: false
 mathjax: false
future: true
jailed: false
gfm_quirks: paragraph_end

highlighter: rouge

markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      include_side_nav: true
      include_math_jax: false
      include_jquery: false
      include_plotlyjs: false
      layout: "default"